void main(
	float3 position,
	float2 texcoord,
	float4 color,
	column_major uniform float4x4 wvp,
	float4 out vPosition : POSITION,
	float out vFog : FOG,
	float2 out vTexcoord : TEXCOORD0,
	float4 out vColor : COLOR)
{
	vPosition = mul(float4(position, 1.f), wvp);
	
	float dist = distance(vPosition,float4(0.0,0.0,0.0,1.0));
	vFog = ((512.0 - dist) / (512.0));
	
	vTexcoord = texcoord;
	vColor = color;
}
